apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: galgu4ccf-nodejs
  janus-idp.io/tekton: galgu4ccf-nodejs
  backstage.io/kubernetes-id: galgu4ccf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: galgu4ccf-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
