apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: galgu4ccf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: galgu4ccf-nodejs 
  name: galgu4ccf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: galgu4ccf-nodejs 
